server:
  port: 8004
  max-http-header-size: 10000KB
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  dbcp:
    max-active: 20
    max-wait: 60000
    initial-size: 1
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.13.108:3306/malphite?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource
springdoc:
  swagger-ui:
    path: /swagger-ui.html
